const detail = [
    {
        id: "aa",
        make: "0121",
        key: "EDI-A08",
        model: "Celica",
        type: ".xls",
        scope: "dept1",
        desc: "PR Coating(ArF/ EUV, UDO)",
        owner: "KP0T11",
        date: "24/08/2008",
        tcount: 3,
    },
    {
        id: "bb",
        make: "0125",
        key: "EDI-A11",
        model: "Mondeo",
        type: ".ppt",
        scope: "dept2",
        desc: "PR Coating (KrF / Arf / Imme)",
        owner: "KP0T11",
        date: "24/08/2008",
        tcount: 2,
        selected: true,
    },
    {
        id: "cc",
        make: "0124",
        key: "EDI-A14",
        model: "Boxster",
        type: ".pdf",
        scope: "de88",
        desc: "",
        owner: "PA091",
        date: "24/08/2008",
        tcount: 5,
    },
    {
        id: "dd",
        make: "0126",
        key: "EDI-D11",
        model: "Angel",
        type: ".xls",
        scope: "dept1",
        desc: "Use for ETCH1 pre-hookup tools",
        owner: "KF0T21",
        date: "24/08/2008",
        tcount: 6,
    },
    {
        id: "ee",
        make: "0128",
        key: "EDI-A17",
        model: "Challanger",
        type: ".doc",
        scope: "de88",
        desc: "PR Coating",
        owner: "KP0T11",
        date: "24/08/2008",
        tcount: 0,
    },
    {
        id: "ff",
        make: "0150",
        key: "PHK",
        model: "Kristin",
        type: ".xls",
        scope: "dept3",
        desc: "",
        owner: "KP02A1",
        date: "24/08/2008",
        tcount: 1,
        selected: true,
    },
];

const sop = [
    {
        id: "aa",
        make: "0121",
        key: "EDI-A08",
        model: "Celica",
        desc: "PR Coating(ArF/ EUV, UDO)",
        scount: 2,
    },
    {
        id: "bb",
        make: "0125",
        key: "EDI-A11",
        model: "Mondeo",
        desc: "PR Coating (KrF / Arf / Imme)",
        scount: 5,
    },
    {
        id: "cc",
        make: "0124",
        key: "EDI-A14",
        model: "Boxster",
        desc: "",
        scount: 4,
    },
    {
        id: "dd",
        make: "0126",
        key: "EDI-D11",
        model: "Angel",
        desc: "Use for ETCH1 pre-hookup tools",
        scount: 6,
    },
    {
        id: "ee",
        make: "0128",
        key: "EDI-A17",
        model: "Challanger",
        desc: "PR Coating",
        scount: 0,
    },
    {
        id: "ff",
        make: "0150",
        key: "PHK",
        model: "Kristin",
        desc: "",
        scount: 1,
    },
];

const bySop = [
    {
        fab: "F18B",
        dept: "eII",
        file: "F1 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "趙錢孫",
        scope: "",
        update: "2022/1/2",
        count: 3,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F2 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "李周吳",
        scope: "",
        update: "2021/11/12",
        count: 1,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F3 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "鄭王",
        scope: "",
        update: "2000/5/2",
        count: 2,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F4 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "李周吳",
        scope: "",
        update: "2011/7/20",
        count: 6,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F5 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "趙錢孫",
        scope: "",
        update: "2002/10/7",
        count: 2,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F6 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "鄭王",
        scope: "",
        update: "1990/6/8",
        count: 3,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F7 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "李周吳",
        scope: "",
        update: "2019/2/18",
        count: 1,
    },
    {
        fab: "F18B",
        dept: "eII",
        file: "F8 Pre-hookup sop.ptt",
        desc: "File Description",
        owner: "趙錢孫",
        scope: "",
        update: "2012/8/23",
        count: 2,
    },
];

const detailSop = [
    {
        taskId: "0121",
        keyStage: "PHK",
        taskName: "自動接水",
        desc: "loeran sdkill Oehi tail dtest",
    },
    {
        taskId: "0122",
        keyStage: "PHK",
        taskName: "自動接水",
        desc: "loeran sdkill Oehi tail dtest",
    },
    {
        taskId: "0125",
        keyStage: "T1",
        taskName: "自動接水",
        desc: "loeran sdkill Oehi tail dtest",
        selected: true,
    },
    {
        taskId: "0129",
        keyStage: "T0",
        taskName: "自動接水",
        desc: "loeran sdkill Oehi tail dtest",
    },
];

module.exports = {
    detail,
    sop,
    bySop,
    detailSop,
};
