const detail = [
    {
        id: "aa",
        make: "0121",
        key: "EDI-A08",
        model: "Celica",
        type: ".xls",
        scope: "dept1",
        desc: "PR Coating(ArF/ EUV, UDO)",
        owner: "KP0T11",
        date: "24/08/2008",
        tcount: 3,
    },
    {
        id: "bb",
        make: "0125",
        key: "EDI-A11",
        model: "Mondeo",
        type: ".ppt",
        scope: "dept2",
        desc: "PR Coating (KrF / Arf / Imme)",
        owner: "KP0T11",
        date: "24/08/2008",
        tcount: 2,
        selected: true,
    },
    {
        id: "cc",
        make: "0124",
        key: "EDI-A14",
        model: "Boxster",
        type: ".pdf",
        scope: "de88",
        desc: "",
        owner: "PA091",
        date: "24/08/2008",
        tcount: 5,
    },
    {
        id: "dd",
        make: "0126",
        key: "EDI-D11",
        model: "Angel",
        type: ".xls",
        scope: "dept1",
        desc: "Use for ETCH1 pre-hookup tools",
        owner: "KF0T21",
        date: "24/08/2008",
        tcount: 6,
    },
    {
        id: "ee",
        make: "0128",
        key: "EDI-A17",
        model: "Challanger",
        type: ".doc",
        scope: "de88",
        desc: "PR Coating",
        owner: "KP0T11",
        date: "24/08/2008",
        tcount: 0,
    },
    {
        id: "ff",
        make: "0150",
        key: "PHK",
        model: "Kristin",
        type: ".xls",
        scope: "dept3",
        desc: "",
        owner: "KP02A1",
        date: "24/08/2008",
        tcount: 1,
        selected: true,
    },
];

const sop = [
    {
        id: "aa",
        make: "0121",
        key: "EDI-A08",
        model: "Celica",
        desc: "PR Coating(ArF/ EUV, UDO)",
        scount: 2,
    },
    {
        id: "bb",
        make: "0125",
        key: "EDI-A11",
        model: "Mondeo",
        desc: "PR Coating (KrF / Arf / Imme)",
        scount: 5,
    },
    {
        id: "cc",
        make: "0124",
        key: "EDI-A14",
        model: "Boxster",
        desc: "",
        scount: 4,
    },
    {
        id: "dd",
        make: "0126",
        key: "EDI-D11",
        model: "Angel",
        desc: "Use for ETCH1 pre-hookup tools",
        scount: 6,
    },
    {
        id: "ee",
        make: "0128",
        key: "EDI-A17",
        model: "Challanger",
        desc: "PR Coating",
        scount: 0,
    },
    {
        id: "ff",
        make: "0150",
        key: "PHK",
        model: "Kristin",
        desc: "",
        scount: 1,
    },
];

module.exports = {
    detail,
    sop,
};
